name: "Build & Test"
concurrency: ${{ github.workflow }}
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: colmanfranco/ms-teams-notification@v2
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Deployment Started 
        notification-color: 17a2b8
        timezone: Europe/Madrid
    - uses: colmanfranco/ms-teams-notification@v2
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Warning! Something Not Quite Right 
        notification-color: ffc107
        timezone: Europe/Madrid
    - uses: colmanfranco/ms-teams-notification@v2
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: OMG!! Something Exploded
        notification-color: dc3545
        timezone: Europe/Madrid
    - uses: colmanfranco/ms-teams-notification@v2
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Whew! Everything is right with the world again! 
        notification-color: 28a745 
        timezone: Europe/Madrid
    - uses: colmanfranco/ms-teams-notification@v2
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: "Emojify! &#x1F6A2​​ &#x2705;"
        notification-color: 28a745 
        timezone: Europe/Madrid