name: "Build & Test"
concurrency: ${{ github.workflow }}
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        npm run all
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tgymnich/publish-github-action@v1.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: colmanfranco/ms-teams-notification@v2.0.4
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Deployment Started 
        notification-color: 17a2b8
        timezone: Europe/Madrid